apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: traefik
    repoURL: https://github.com/bernardzzz/argocd-poc-tools.git
    targetRevision: main
  syncPolicy:
    automated: {}
  values:
    - values.yaml
