apiVersion: v2
name: traefik
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: traefik
    version: 1.7.9
    repository: https://helm.traefik.io/traefik